set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(VCPKG_ENV_PASSTHROUGH PATH)

set(VCPKG_CMAKE_CONFIGURE_OPTIONS)

if(NOT DEFINED CMAKE_C_COMPILER)
    find_program(CMAKE_C_COMPILER gcc)
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER)
    find_program(CMAKE_CXX_COMPILER g++)
endif()

set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DCMAKE_SYSTEM_PROCESSOR=AMD64
    -DCMAKE_C_FLAGS=-D_UCRT
    -DCMAKE_CXX_FLAGS=-D_UCRT
    -DBUILD_SHARED_LIBS=OFF
)

set(VCPKG_CMAKE_CONFIGURE_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS}
    -G Ninja
)

